require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ModuleFunction:
  Enabled: true
  EnforcedStyle: extend_self

Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
