FROM ruby:3-slim

RUN apt-get update && apt-get install -y \
  zlib1g-dev \
  liblzma-dev \
  build-essential \
  curl \
  git

ENV APP_NAME retainer
ENV APP_HOME /app/$APP_NAME
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
